[package]
name = "quiz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
termion = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "3.0"

